Repository clearwater-labs/parkingNotifier, pull requests merged in 2019-02, with the labels that each got.

#131 Updated parking status docs
  api/routes/parkingStatus.yaml
Labels: review

#132 Updated confirm email error message
  frontend/src/components/ConfirmEmail.js
Labels: review

#133 Fix DB connection
  api/server.js
Labels: review

#137 Allow Frontend to Persist when API is down
  api/package-lock.json
  api/package.json
  frontend/src/components/DownAlert.js
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/unsubscribe.js
Labels: review

#139 RELEASE 2.1
  api/package-lock.json
  api/package.json
  frontend/src/components/DownAlert.js
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/unsubscribe.js
Labels: review

#141 Fix Down API Handler
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/unsubscribe.js
Labels: FRONTEND, bug, review

#142 v2.1.1: Fix Down API Handler
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/unsubscribe.js
Labels: RELEASE, review

#144 Fix broken count bug
  frontend/src/components/Home.js
  frontend/src/components/Register.js
Labels: review

#145 v2.1.1
  frontend/src/components/Home.js
  frontend/src/components/Register.js
Labels: review

#148 Switch to secure api calls
  frontend/src/components/ConfirmEmail.js
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/unsubscribe.js
Labels: review

#149 v2.1.2
  frontend/src/components/ConfirmEmail.js
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/unsubscribe.js
Labels: review

#154 Fix https calls
  frontend/src/components/ConfirmEmail.js
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/helpers/api.js
  frontend/src/components/unsubscribe.js
Labels: review

#152 Fixed scrape when database is empty
  api/helpers/monitor.js
Labels: review

#155 v2.2
  api/helpers/monitor.js
  frontend/src/components/ConfirmEmail.js
  frontend/src/components/Home.js
  frontend/src/components/Register.js
  frontend/src/components/helpers/api.js
  frontend/src/components/unsubscribe.js
Labels: review

#162 Fix Twilio Bug
  api/helpers/notify.js
  api/server.js
Labels: review

#166 Cleanup /status endpoint
  api/controllers/parkingStatus.js
Labels: API, review

#163 Monitor.js diagram and code clean up
  api/helpers/monitor.js
  docs/README.md
  docs/monitorDiagram.png
Labels: review

#176 Fix for inaccurate logging due to timezone differences
  api/controllers/parkingStatus.js
  api/helpers/monitor.js
  api/routes/parkingStatus.js
  api/server.js
Labels: review

#186 add brandon and some links
  frontend/src/components/About.js
  frontend/src/media/brandon_pessman.jpg
  frontend/src/media/grey_larson.jpg
Labels: review

#187 Release 2.2
  api/controllers/parkingStatus.js
  api/helpers/monitor.js
  api/helpers/notify.js
  api/package-lock.json
  api/package.json
  api/routes/parkingStatus.js
  api/server.js
  docs/README.md
  docs/monitorDiagram.png
  frontend/package-lock.json
  frontend/src/components/About.js
  frontend/src/media/brandon_pessman.jpg
  frontend/src/media/grey_larson.jpg
Labels: review

#189 Updated scrape for new website
  api/helpers/monitor.js
Labels: review
