Repository clearwater-labs/parkingNotifier, pull requests merged in 2019-01, with the labels that each got.

#66 Add Waffle Badge
  README.md
  api/helpers/notify.js
Labels: review

#62 Only send notifications to users that are subscribed
  api/helpers/notify.js
Labels: review

#67 Show email in UI
  api/helpers/notify.js
  frontend/src/components/Register.js
Labels: in progress, review

#69 /users and users/subscribed/ authentication checking for dashboard use
  api/controllers/users.js
  api/package-lock.json
  api/package.json
  api/routes/users.js
Labels: review

#70 68 webscrape update
  api/helpers/monitor.js
Labels: Parking Notifier, review

#72 Update docs
  api/controllers/users.js
  api/mocha.opts
  api/package-lock.json
  api/package.json
  api/redoc.html
  api/routes/stats.yaml
  api/routes/status.yaml
  api/routes/users.js
  api/routes/users.yaml
  api/server.js
  api/swaggerConfig.js
  docs/technical-details.md
Labels: Parking Notifier, review

#91 updated the responsiveness of a few items for better mobile friendliness
  frontend/src/App.css
Labels: review

#93 92 frontend updates
  frontend/src/App.css
  frontend/src/components/About.js
  frontend/src/components/Register.js
  frontend/src/media/demo_text_2.png
Labels: review

#96 Remove extra dollar sign
  frontend/src/components/Register.js
Labels: review

#108 Auth fix & docs
  api/redoc.html
  api/routes/users.js
  api/routes/users.yaml
  api/server.js
  api/swaggerConfig.js
Labels: review

#109 change address
  api/redoc.html
  api/server.js
Labels: review

#112 Count shows confirmed users
  frontend/src/components/Home.js
  frontend/src/components/Register.js
Labels: review

#114 example text image disappears after register
  frontend/src/components/Register.js
Labels: review

#120 Fix Bucket Name
  .travis.yml
Labels: review

#122 fix bucket name
  .travis.yml
Labels: review

#113 Refactoring status routes and files, updating status endpoint
  api/controllers/parkingStatus.js
  api/controllers/status.js
  api/helpers/monitor.js
  api/models/parkingStatus.js
  api/models/status.js
  api/package-lock.json
  api/package.json
  api/routes/parkingStatus.js
  api/routes/parkingStatus.yaml
  api/routes/status.js
  api/routes/status.yaml
  api/routes/users.js
  api/routes/users.yaml
  api/server.js
  docker-compose.yml
Labels: review
